### PR TITLE
Fix live tests

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by kentfredric** [comment]
This is probably better handled by `$ENV{NO_NETWORK_TESTING}`, which is something that would be nice if applied more widely over CPAN.

CF: https://metacpan.org/source/MALLEN/Test-RequiresInternet-0.05/lib/Test/RequiresInternet.pm#L11

This is more or less what I have to do downstream anyway, where the test suite may run in a network sandbox at the users request ( which can turn some network IO's into fatal errors )

**Comment by kentfredric** [comment]
Also, the instructions " pass --live-tests to Makefile.PL to enable" are now dated, and should be removed.

**Comment by kentfredric** [comment]
My local branch I've used as a reference for fixing our downstream patches is :

https://github.com/libwww-perl/Net-HTTP/compare/v6.12...kentfredric:prefer-nohttp

It hybridizes commits in this PR with my own alternative to the other.

Tested and behaves as expected in the following conditions:

1. Under network sandbox with NO_NETWORK_TESTING set ( does not try any TCP magic )
2. Under network sandbox without NO_NETWORK_TESTING set ( tries TCP magic, but guards detect TCP can't dial out and intelligently skips
3. Outside network sandbox without NO_NETWORK_TESTING set ( does full network IO )

I'd send a PR, but this is probably a job for careful cherry-picking ( though I can send it as-is on request )

**Comment by genio** [comment]
I agree with @kentfredric. The ```--live-tests``` option should be done away with in favor of environment variables. 297fcb1 looks good, though.

**Comment by oalders** [comment]
@kentfredric what you've done looks good to me.  How is your approach different from just using `Test::RequiresInternet`, which also respects `$ENV{NO_NETWORK_TESTING}`?

**Comment by kentfredric** [comment]
My approach is basically that, but more light-weight, in that:

- It doesn't requre a dependency
- It doesn't even need to load Test::More to enter the "skip this" situation.

This is mostly optimising to avoid loading all of Test2, which can be slow, to simply do nothing.

**Comment by oalders** [comment]
@kentfredric did you want to send a PR with your changes?  They look good to me.

**Pull request merged**
